version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestor-php
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    networks:
      - gestor_net
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: gestor-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestor
      MYSQL_USER: gestoruser
      MYSQL_PASSWORD: gestorpass
      TZ: America/Bogota
    volumes:
      - db_data:/var/lib/mysql
      - ./data/bd.sql:/docker-entrypoint-initdb.d/bd.sql
    ports:
      - '3307:3306'
    networks:
      - gestor_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gestor-pma
    environment:
      PMA_HOST: db
      PMA_USER: gestoruser
      PMA_PASSWORD: gestorpass
      UPLOAD_LIMIT: 100M
    ports:
      - '8081:80'
    depends_on:
      - db
    networks:
      - gestor_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    ports:
      - '8082:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    privileged: true
    restart: unless-stopped
    networks:
      - gestor_net

networks:
  gestor_net:

volumes:
  db_data:
  jenkins_data:
