services:
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: gestor-php
    volumes:
      - .:/var/www/html
    networks:
      - gestor_net

  nginx:
    image: nginx:1.27-alpine
    container_name: gestor-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - gestor_net

  db:
    image: mariadb:11
    container_name: gestor-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=gestor
      - MYSQL_USER=gestoruser
      - MYSQL_PASSWORD=gestorpass
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - gestor_net

  phpmyadmin:
    image: phpmyadmin:5
    container_name: gestor-pma
    environment:
      - PMA_HOST=db
      - PMA_USER=gestoruser
      - PMA_PASSWORD=gestorpass
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - gestor_net

networks:
  gestor_net:
