version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    networks:
      - gestor_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8000:80' # navegador -> puerto 8000
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gestor_net
    depends_on:
      - php

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestor
      MYSQL_USER: gestoruser
      MYSQL_PASSWORD: gestorpass
      TZ: America/Bogota
    volumes:
      - db_data:/var/lib/mysql
      - ./data/bd.sql:/docker-entrypoint-initdb.d/bd.sql
    ports:
      - '3307:3306'
    networks:
      - gestor_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: gestoruser
      PMA_PASSWORD: gestorpass
      UPLOAD_LIMIT: 100M
    ports:
      - '8081:80'
    depends_on:
      - db
    networks:
      - gestor_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - '8082:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    privileged: true
    restart: unless-stopped
    networks:
      - gestor_net

networks:
  gestor_net:

volumes:
  db_data:
  jenkins_data:
